export { Navbar } from './Navbar'
export { Hero } from './Hero'
export { Services } from './Services'
export { WhyChooseUs } from './WhyChooseUs'
export { HowItWorks } from './HowItWorks'
export { Testimonials } from './Testimonials'
export { Contact } from './Contact'
export { Footer } from './Footer'
