export const QUEUE_EVENT_CUSTOMER_CREATE = "event_customer_create";
export const WORKER_EVENT_CUSTOMER_CREATE_CONCURRENCY = 1;
export const WORKER_EVENT_CUSTOMER_CREATE_INTERVAL_DELAY = 2500;

export const QUEUE_EVENT_SERVICE_CREATE = "event_service_create";
export const WORKER_EVENT_SERVICE_CREATE_CONCURRENCY = 1;
export const WORKER_EVENT_SERVICE_CREATE_INTERVAL_DELAY = 2500;
