export const QUEUE_EVENT_CUSTOMER_CREATE = "factor.event_customer_create";
export const WORKER_EVENT_CUSTOMER_CREATE_CONCURRENCY = 1;
export const WORKER_EVENT_CUSTOMER_CREATE_INTERVAL_DELAY = 2500;

export const QUEUE_EVENT_CUSTOMER_UPDATE = "factor.event_customer_update";
export const WORKER_EVENT_CUSTOMER_UPDATE_CONCURRENCY = 1;
export const WORKER_EVENT_CUSTOMER_UPDATE_INTERVAL_DELAY = 2500;

export const QUEUE_EVENT_SERVICE_CREATE = "factor.event_service_create";
export const WORKER_EVENT_SERVICE_CREATE_CONCURRENCY = 1;
export const WORKER_EVENT_SERVICE_CREATE_INTERVAL_DELAY = 2500;

export const QUEUE_EVENT_SERVICE_UPDATE = "factor.event_service_update";
export const WORKER_EVENT_SERVICE_UPDATE_CONCURRENCY = 1;
export const WORKER_EVENT_SERVICE_UPDATE_INTERVAL_DELAY = 2500;
